name: full checkov

on:
  pull_request:
    paths:
      - '**/*.tf'

jobs:
  check-changed-files:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Fetch enough history for comparison

      # Step 2: Find changed Terraform files
      - name: Find changed .tf files
        run: |
          echo "Checking for changed .tf files..."
          git fetch origin main
          CHANGED_FILES=$(git diff --name-only origin/main | grep '\.tf$' || true)
          echo "Changed files: $CHANGED_FILES"
          
          if [ -z "$CHANGED_FILES" ]; then
            echo "No Terraform files changed."
            exit 0
          else
            echo "Terraform files changed:"
            echo "$CHANGED_FILES"
          fi

      # Step 3: Set up Python (required for Checkov)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 4: Install Checkov
      - name: Install Checkov
        run: pip install checkov

      # Step 5: Run Checkov scan on changed .tf files
      - name: Run Checkov on changed files
        if: success() && steps.check-changed-files.outputs.CHANGED_FILES != ''
        run: |
          for file in $CHANGED_FILES; do
            echo "Running Checkov on $file"
            checkov -f $file --output json > checkov_results.json
            CRITICAL_ISSUES=$(jq '[.results.failed_checks[] | select(.severity == "CRITICAL") ] | length' checkov_results.json)
            
            if [ "$CRITICAL_ISSUES" -gt 0 ]; then
              echo "CRITICAL issues found: $CRITICAL_ISSUES"
              echo "::error::Checkov found critical security issues!"
              exit 1
            else
              echo "No critical security issues found."
            fi
          done

      # Step 6: Upload Checkov scan results as a PR comment
      - name: Post Checkov scan results as PR comment
        if: always()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: checkov_results.json
