name: "Terraform Format, Lint & Checkov"

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.tf"
jobs:
  terraform-lint-checkov:
    name: "Terraform Formatting, Linting & Checkov Security Scan"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Identify changed Terraform files
        id: changed-files
        run: |
          if [ "$(git rev-parse --is-shallow-repository)" = "true" ]; then
            git fetch --prune --unshallow
          fi
          CHANGED_FILES=$(git diff --name-only $(git merge-base HEAD main) HEAD | grep '\.tf$' || true)

          if [[ -z "$CHANGED_FILES" ]]; then
            echo "No Terraform files changed. Exiting workflow."
            exit 0
          fi
          echo "Terraform files changed: $CHANGED_FILES"
          echo "TF_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Run terraform fmt (Check Formatting)
        run: terraform fmt -check -diff

      - name: Install tflint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          tflint --init

      - name: Run tflint (Linting)
        run: tflint --recursive

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov security scan
        run: |
          for file in $TF_FILES; do
            checkov -f $file --output cli
          done
