name: "Terraform Format, Lint & Checkov"

on:
  pull_request:
    branches:
      - main  # Runs when a PR is created or updated targeting the main branch
    paths:
      - "**.tf"  # Runs only if Terraform files are modified

jobs:
  terraform-lint-checkov:
    name: "Terraform Formatting, Linting & Checkov Security Scan"
    runs-on: ubuntu-latest  # Runs on a Linux machine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history is fetched

      - name: Identify changed Terraform files
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only --diff-filter=ACMRT origin/${{ github.base_ref }}...HEAD | grep '\.tf$' || true)
          if [[ -z "$CHANGED_FILES" ]]; then
            echo "No Terraform files changed. Exiting workflow."
            exit 0
          fi
          echo "Terraform files changed: $CHANGED_FILES"
          echo "TF_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Run terraform fmt (Check Formatting)
        run: terraform fmt -check -diff

      - name: Install tflint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          tflint --init  # Initialize tflint

      - name: Run tflint (Linting)
        run: tflint --recursive

      - name: Install Checkov
        if: env.TF_FILES != ''
        run: pip install checkov

      - name: Run Checkov security scan
        if: env.TF_FILES != ''
        run: |
          for file in $TF_FILES; do
            checkov -f $file --output cli
          done

      - name: Post scan results as PR comment
        if: env.TF_FILES != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMMENT="**Terraform Lint & Checkov Results**:\n"
          COMMENT+=$(terraform fmt -check -diff $TF_FILES)
          COMMENT+=$(for file in $TF_FILES; do tflint --filter=$(dirname $file); done)
          COMMENT+=$(for file in $TF_FILES; do checkov -f $file --output cli; done)
          echo "$COMMENT" | gh pr comment ${{ github.event.number }} --body -
