name: Check Changed Terraform Files

on:
  pull_request:
    paths:
      - '**/*.tf'

jobs:
  check-changed-files:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Fetch enough history for comparison

      # Step 2: Find changed Terraform files
      - name: Find changed .tf files
        run: |
          echo "Checking for changed .tf files..."
          git fetch origin main
          CHANGED_FILES=$(git diff --name-only origin/main | grep '\.tf$' || true)
          echo "Changed files: $CHANGED_FILES"
          
          if [ -z "$CHANGED_FILES" ]; then
            echo "No Terraform files changed."
            exit 0
          else
            echo "Terraform files changed:"
            echo "$CHANGED_FILES"
          fi
