name: "Terraform Format & Lint"

on:
  pull_request:
    paths:
      - '**/*.tf' # Trigger only when Terraform files change
    branches:
      - main  # Change this to 'master' or your repo's default branch

jobs:
  terraform-lint:
    name: "Terraform Formatting & Linting"
    runs-on: ubuntu-latest  # Runs on GitHub-hosted Linux machine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Identify changed Terraform files
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }} HEAD | grep '\.tf$' || true)
          if [[ -z "$CHANGED_FILES" ]]; then
            echo "No Terraform files changed."
            exit 0
          fi
          echo "Changed Terraform files: $CHANGED_FILES"
          echo "FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Run terraform fmt
        run: |
          terraform fmt -check -diff $FILES

      - name: Install tflint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Run tflint
        run: |
          for file in $FILES; do
            tflint --filter=$(dirname $file)
          done
