name: Run on Push
 
on:
  push:
    branches:
      - test  # Change this to your branch if needed
 
jobs:
  run-something:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
     
      - name: Run a Sample Command
        run: echo "Code pushed! Running something..."